  server:
    port: 3000
  spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo_database
        username: root
        password:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update